services:
  frontend:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./frontend_data:/usr/share/nginx/html

  backend:
    image: nginx:alpine
    ports:
      - 8082:80
    volumes:
      - ./backend_data:/usr/share/nginx/html
